name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches: main
env:
  GO_VERSION: '1.22.1'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Clone Carcassone-Engine
        run: git clone https://github.com/YetAnotherSpieskowcy/Carcassonne-Engine.git
      - name: Run tests
        run: ENGINE_PATH="./Carcassonne-Engine" make test
